/**
 * PrismaService
 *
 * This service provides a Prisma client instance for interacting with the database.
 * It extends the PrismaClient class generated by Prisma, allowing easy access to
 * database operations. The configuration is handled using the NestJS ConfigService.
 *
 * @class
 * @extends {PrismaClient}
 * @implements {Injectable}
 */
import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { PrismaClient } from '@prisma/client';

@Injectable()
export class PrismaService extends PrismaClient {
  /**
   * PrismaService Constructor
   *
   * @constructor
   * @param {ConfigService} config - The ConfigService instance for retrieving configuration values.
   */
  constructor(config: ConfigService) {
    super({
      datasources: {
        db: {
          // Set the database connection URL from the configuration
          url: config.get('DATABASE_URL'),
        },
      },
    });
  }
}
